import { useState } from 'react'
import { Printer } from 'lucide-react'
import { useActiveProject, useStageEditor } from '@/state/AppContext'
import { asExample, FieldCoach, TextArea } from '@/components/ui'
import { StageFlow, type WizardStep } from '@/components/StageFlow'
import { UpgradeModal, UpgradePrompt } from '@/components/UpgradeModal'
import { usePlan } from '@/state/PlanContext'
import { coaching } from '@/data/coaching'
import { avgRisk, preparedness, riskLabel } from '@/lib/format'
import { brandOf, brandVars } from '@/lib/brand'
import { getLang, htmlLang, t, tp } from '@/i18n'

const longDate = (d: Date) => d.toLocaleDateString(htmlLang(getLang()), { month: 'long', day: 'numeric', year: 'numeric' })
const prepColor = (p: number) => (p >= 80 ? '#22c55e' : p >= 50 ? '#f59e0b' : '#ef4444')

export function ReportStage() {
  const project = useActiveProject()
  const { data: closeout, update } = useStageEditor('closeout')
  const { isPro, loading: planLoading } = usePlan()
  const [upsell, setUpsell] = useState(false)
  if (!project) return null

  const sd = project.stageData
  const prep = preparedness(project)
  const avg = avgRisk(sd.risk.items)
  const brand = brandOf(project, isPro)
  const locked = !isPro || planLoading
  const metrics = sd.adoption.metrics.filter((m) => m.name)
  const onTarget = metrics.filter((m) => {
    const c = parseFloat(m.current)
    const target = parseFloat(m.target)
    return isFinite(c) && isFinite(target) && target !== 0 && c / target >= 0.8
  }).length
  const goLive = sd.milestones.goLiveDate
    ? new Date(sd.milestones.goLiveDate + 'T00:00:00').toLocaleDateString(htmlLang(getLang()), { month: 'short', day: 'numeric', year: 'numeric' })
    : '-'

  const fc = coaching.closeout.fields

  // The editable closeout reflections (feed the printable report below) run
  // through the guided/summary flow; the report itself always renders beneath.
  const steps: WizardStep[] = [
    {
      id: 'wins',
      title: t('Wins'),
      isFilled: !!closeout.wins.trim(),
      summary: closeout.wins,
      node: (
        <FieldCoach label={fc.wins.label} why={fc.wins.why}>
          <TextArea value={closeout.wins} onCommit={(v) => update({ wins: v })} placeholder={asExample(fc.wins.example)} rows={3} />
        </FieldCoach>
      ),
    },
    {
      id: 'lessons',
      title: t('Lessons'),
      isFilled: !!closeout.lessons.trim(),
      summary: closeout.lessons,
      node: (
        <FieldCoach label={fc.lessons.label} why={fc.lessons.why}>
          <TextArea value={closeout.lessons} onCommit={(v) => update({ lessons: v })} placeholder={asExample(fc.lessons.example)} rows={3} />
        </FieldCoach>
      ),
    },
    {
      id: 'shoutouts',
      title: t('Shout-outs'),
      isFilled: !!closeout.shoutouts.trim(),
      summary: closeout.shoutouts,
      node: (
        <FieldCoach label={fc.shoutouts.label} why={fc.shoutouts.why}>
          <TextArea value={closeout.shoutouts} onCommit={(v) => update({ shoutouts: v })} placeholder={asExample(fc.shoutouts.example)} rows={2} />
        </FieldCoach>
      ),
    },
  ]

  return (
    <div>
      <StageFlow stageId="executive" icon={coaching.report.icon} blurb={coaching.report.intro} steps={steps} />

      {/* Sits directly above the report they're about to print, which is where
          the Adaptus footer is staring back at them. Outside `.print-area`, so
          it never reaches the printed page. */}
      {locked && (
        <UpgradePrompt
          title={t('Print this and it says “Generated by Adaptus”')}
          body={t('Pro puts your own logo and colour on the report instead, with no mark of ours anywhere on it.')}
          cta={t('See Pro')}
          onUpgrade={() => setUpsell(true)}
        />
      )}

      <button
        type="button"
        onClick={() => window.print()}
        style={{ display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'linear-gradient(135deg,#5B86A3,#3E6580)', border: 'none', borderRadius: '10px', padding: '12px 26px', color: 'var(--on-accent)', fontWeight: 600, fontSize: '14px', cursor: 'pointer', margin: '8px 0 20px', fontFamily: 'inherit' }}
      >
        <Printer size={16} /> {t('Print / Save as PDF')}
      </button>

      {/* The printable report */}
      <div className="print-area">
        <div className="brief-wrap" style={brandVars(brand)}>
          <div className="brief-hdr">
            <div className="brief-badge">{tp('{pct}% prepared', { pct: prep.pct })}</div>
            {brand.logo && <img className="brief-logo" src={brand.logo} alt="" />}
            <h1>{project.name}</h1>
            <div className="bm">{project.type ? t(project.type) : t('Change project')} · {t('Launch Success Report')} · {longDate(new Date())}</div>
          </div>
          <div className="brief-body">
            {/* Outcome */}
            <div className="bs">
              <div className="bst">{t('Launch Outcome')}</div>
              <div className="bsg">
                <div className="bsc"><div className="v" style={{ color: prepColor(prep.pct) }}>{prep.pct}%</div><div className="l">{t('Preparedness')}</div></div>
                <div className="bsc"><div className="v">{goLive}</div><div className="l">{t('Go-live')}</div></div>
                <div className="bsc"><div className="v">{metrics.length ? `${onTarget}/${metrics.length}` : '-'}</div><div className="l">{t('Metrics on target')}</div></div>
              </div>
            </div>

            {/* Change summary */}
            {(sd.define.statement || sd.define.whyNow) && (
              <div className="bs">
                <div className="bst">{t('What We Changed')}</div>
                {sd.define.statement && <p style={{ fontSize: '14px', color: 'rgba(255,255,255,0.78)', lineHeight: 1.7 }}>{sd.define.statement}</p>}
                {sd.define.successLooks && (
                  <div style={{ marginTop: '10px', background: 'rgba(34,197,94,0.08)', borderLeft: '3px solid #22c55e', borderRadius: '0 8px 8px 0', padding: '10px 14px', fontSize: '13px', color: 'rgba(255,255,255,0.7)', lineHeight: 1.6 }}>
                    <span style={{ fontSize: '11px', fontWeight: 700, color: '#22c55e', textTransform: 'uppercase', letterSpacing: '1px', display: 'block', marginBottom: '4px' }}>{t('Goal we set')}</span>
                    {sd.define.successLooks}
                  </div>
                )}
              </div>
            )}

            {/* Adoption */}
            {metrics.length > 0 && (
              <div className="bs">
                <div className="bst">{t('Adoption')}</div>
                {metrics.map((m) => {
                  const c = parseFloat(m.current)
                  const target = parseFloat(m.target)
                  const p2 = isFinite(c) && isFinite(target) && target !== 0 ? Math.min(100, Math.round((c / target) * 100)) : 0
                  return (
                    <div key={m.id} style={{ marginBottom: '12px' }}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: '5px' }}>
                        <span style={{ fontSize: '13px', color: 'rgba(255,255,255,0.8)' }}>{m.name}</span>
                        <span style={{ fontSize: '13px', color: '#B8D0DE', fontWeight: 700 }}>{m.current ? `${m.current}${t(m.unit)} / ${m.target}${t(m.unit)}` : ''}</span>
                      </div>
                      {m.current && m.target && (
                        <div style={{ height: '8px', background: 'rgba(255,255,255,0.06)', borderRadius: '4px', overflow: 'hidden' }}>
                          <div style={{ height: '100%', width: `${p2}%`, background: p2 >= 80 ? '#22c55e' : p2 >= 50 ? '#f59e0b' : '#5B86A3', borderRadius: '4px' }} />
                        </div>
                      )}
                    </div>
                  )
                })}
              </div>
            )}

            {/* Risk recap */}
            {avg !== null && (
              <div className="bs">
                <div className="bst">{t('Risk Going In')}</div>
                <span className="btag b">{tp('{level} risk · {score}/10', { level: t(riskLabel(avg)), score: avg })}</span>
              </div>
            )}

            {/* Wins / lessons / shoutouts */}
            {closeout.wins && (
              <div className="bs">
                <div className="bst">{t('What Went Well')}</div>
                <p style={{ fontSize: '13px', color: 'rgba(255,255,255,0.78)', lineHeight: 1.7, whiteSpace: 'pre-wrap' }}>{closeout.wins}</p>
              </div>
            )}
            {closeout.lessons && (
              <div className="bs">
                <div className="bst">{t("What We'd Do Differently")}</div>
                <p style={{ fontSize: '13px', color: 'rgba(255,255,255,0.78)', lineHeight: 1.7, whiteSpace: 'pre-wrap' }}>{closeout.lessons}</p>
              </div>
            )}
            {closeout.shoutouts && (
              <div className="bs">
                <div className="bst">{t('Shoutouts')}</div>
                <p style={{ fontSize: '13px', color: 'rgba(255,255,255,0.78)', lineHeight: 1.7, whiteSpace: 'pre-wrap' }}>{closeout.shoutouts}</p>
              </div>
            )}

            {/* Sustainment */}
            {(sd.sustainment.reinforcementOwner || sd.sustainment.metrics) && (
              <div className="bs">
                <div className="bst">{t('Keeping It Sticking')}</div>
                {sd.sustainment.reinforcementOwner && <p style={{ fontSize: '13px', color: 'rgba(255,255,255,0.78)', lineHeight: 1.7 }}><strong style={{ color: '#fff' }}>{t('Owner:')}</strong> {sd.sustainment.reinforcementOwner}</p>}
                {sd.sustainment.metrics && <p style={{ fontSize: '13px', color: 'rgba(255,255,255,0.7)', lineHeight: 1.7, marginTop: '4px' }}>{sd.sustainment.metrics}</p>}
              </div>
            )}
          </div>
          <div className="brief-ft">
            <div style={{ fontSize: '11px', color: 'rgba(255,255,255,0.3)' }}>
              {brand.whiteLabel ? longDate(new Date()) : `${t('Generated by Adaptus')} · ${longDate(new Date())}`}
            </div>
          </div>
        </div>
      </div>

      {upsell && <UpgradeModal reason={t('Reports you print or hand out carry the Adaptus mark on the free plan. Pro replaces it with your own.')} onClose={() => setUpsell(false)} />}
    </div>
  )
}
